username: "YOUR_USERNAME"
password_hash: "YOUR_PASSWORD_SHA1_HASH" # or you can use plain password field "password"
password: "YOUR_PLAIN_PASSWORD"

devices:
  - pn: "Q00000000001" # set your target pn
#  - pn: "Q00000000002" # you can set many targets, or one

mqtt:
  host: "localhost"
  port: 1883
  user: ""
  pass: ""
  base_topic: "home/inverters"

poll_interval: 60  # seconds, smartess updates cloud data with default 5 minutes interval